import { pgTable, text, timestamp, jsonb, varchar, integer, boolean, index } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

export const musicGenerations = pgTable('music_generations', {
    id: text('id').primaryKey(),
    taskId: text('task_id').notNull().unique(),

    // Form data
    recipient: text('recipient'),
    relationship: text('relationship'),
    tone: text('tone'),
    vibe: text('vibe'),
    style: text('style'),
    story: text('story'),
    personalization: text('personalization'),
    length: text('length'),
    includeName: text('include_name'),

    // Generated prompt
    generatedPrompt: text('generated_prompt'),

    // MusicGPT response data
    conversionId1: text('conversion_id_1'),
    conversionId2: text('conversion_id_2'),
    status: varchar('status', { length: 50 }).notNull().default('pending'),

    // Audio URLs
    audioUrl1: text('audio_url_1'),
    audioUrl2: text('audio_url_2'),
    audioUrlWav1: text('audio_url_wav_1'),
    audioUrlWav2: text('audio_url_wav_2'),

    // Metadata
    title1: text('title_1'),
    title2: text('title_2'),
    lyrics1: text('lyrics_1'),
    lyrics2: text('lyrics_2'),
    duration1: integer('duration_1'),
    duration2: integer('duration_2'),
    albumCoverUrl: text('album_cover_url'),

    // Full API responses (for debugging)
    musicGptResponse: jsonb('musicgpt_response'),
    statusResponse: jsonb('status_response'),

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
    completedAt: timestamp('completed_at'),
});

export type MusicGeneration = typeof musicGenerations.$inferSelect;
export type NewMusicGeneration = typeof musicGenerations.$inferInsert;

// Better Auth tables (generated by @better-auth/cli)
export const user = pgTable("user", {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),
    emailVerified: boolean("email_verified").default(false).notNull(),
    image: text("image"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
        .defaultNow()
        .$onUpdate(() => new Date())
        .notNull(),
});

export const session = pgTable(
    "session",
    {
        id: text("id").primaryKey(),
        expiresAt: timestamp("expires_at").notNull(),
        token: text("token").notNull().unique(),
        createdAt: timestamp("created_at").defaultNow().notNull(),
        updatedAt: timestamp("updated_at")
            .$onUpdate(() => new Date())
            .notNull(),
        ipAddress: text("ip_address"),
        userAgent: text("user_agent"),
        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
    },
    (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
    "account",
    {
        id: text("id").primaryKey(),
        accountId: text("account_id").notNull(),
        providerId: text("provider_id").notNull(),
        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        accessToken: text("access_token"),
        refreshToken: text("refresh_token"),
        idToken: text("id_token"),
        accessTokenExpiresAt: timestamp("access_token_expires_at"),
        refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
        scope: text("scope"),
        password: text("password"),
        createdAt: timestamp("created_at").defaultNow().notNull(),
        updatedAt: timestamp("updated_at")
            .$onUpdate(() => new Date())
            .notNull(),
    },
    (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
    "verification",
    {
        id: text("id").primaryKey(),
        identifier: text("identifier").notNull(),
        value: text("value").notNull(),
        expiresAt: timestamp("expires_at").notNull(),
        createdAt: timestamp("created_at").defaultNow().notNull(),
        updatedAt: timestamp("updated_at")
            .defaultNow()
            .$onUpdate(() => new Date())
            .notNull(),
    },
    (table) => [index("verification_identifier_idx").on(table.identifier)],
);

// Relations
export const userRelations = relations(user, ({ many }) => ({
    sessions: many(session),
    accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
    user: one(user, {
        fields: [session.userId],
        references: [user.id],
    }),
}));

export const accountRelations = relations(account, ({ one }) => ({
    user: one(user, {
        fields: [account.userId],
        references: [user.id],
    }),
}));

// Type exports
export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;
export type Account = typeof account.$inferSelect;
export type Session = typeof session.$inferSelect;
